# Generated by Django 4.2.2 on 2023-07-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_name', models.CharField(max_length=100, null=True)),
                ('cargo_weight', models.CharField(max_length=100, null=True)),
                ('cargo_value', models.CharField(max_length=100, null=True)),
                ('sending_date', models.DateField(null=True)),
                ('loading_location', models.CharField(max_length=400, null=True)),
                ('loading_time', models.TimeField(blank=True, null=True)),
                ('unloading_place', models.CharField(max_length=400, null=True)),
                ('unloading_time', models.TimeField(blank=True, null=True)),
                ('car_box', models.CharField(max_length=400, null=True)),
                ('loading_car', models.CharField(blank=True, max_length=400, null=True)),
                ('unloading_car', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
    ]
